[project]
name = "openapi-tools-csharp-nullable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.2",
    "pydantic>=1.0.0",
    "uvicorn>=0.32.0",
]
