/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HelloWorldResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HelloWorldResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HelloWorldResponse
        //private HelloWorldResponse instance;

        public HelloWorldResponseTests()
        {
            // TODO uncomment below to create an instance of HelloWorldResponse
            //instance = new HelloWorldResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HelloWorldResponse
        /// </summary>
        [Fact]
        public void HelloWorldResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HelloWorldResponse
            //Assert.IsType<HelloWorldResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
