openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /:
    get:
      operationId: get_root__get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
          description: Successful Response
      summary: Get Root
components:
  schemas:
    HelloWorldResponse:
      example:
        message4: message4
        message3: message3
        message2: message2
        message1: message1
      properties:
        message1:
          nullable: true
          type: string
        message2:
          nullable: true
          type: string
        message3:
          nullable: true
          type: string
        message4:
          nullable: true
          type: string
      required:
      - message1
      - message3
      title: HelloWorldResponse

