openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /:
    get:
      operationId: get_root__get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
          description: Successful Response
      summary: Get Root
components:
  schemas:
    HelloWorldResponse:
      example:
        message4: 2000-01-23T04:56:07.000+00:00
        message3: 2000-01-23T04:56:07.000+00:00
        message2: 2000-01-23T04:56:07.000+00:00
        message1: 2000-01-23T04:56:07.000+00:00
      properties:
        message1:
          format: date-time
          title: Message1
          type: string
        message2:
          format: date-time
          title: Message2
          type: string
        message3:
          format: date-time
          title: Message3
          type: string
        message4:
          format: date-time
          title: Message4
          type: string
      title: HelloWorldResponse

