/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using API.Backend.Api;
using API.Backend.Model;
using API.Backend.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace API.Backend.Test.Model
{
    /// <summary>
    ///  Class for testing HelloWorldResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HelloWorldResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HelloWorldResponse
        //private HelloWorldResponse instance;

        public HelloWorldResponseTests()
        {
            // TODO uncomment below to create an instance of HelloWorldResponse
            //instance = new HelloWorldResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HelloWorldResponse
        /// </summary>
        [Test]
        public void HelloWorldResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HelloWorldResponse
            //Assert.IsType<HelloWorldResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message1'
        /// </summary>
        [Test]
        public void Message1Test()
        {
            // TODO unit test for the property 'Message1'
        }
        /// <summary>
        /// Test the property 'Message2'
        /// </summary>
        [Test]
        public void Message2Test()
        {
            // TODO unit test for the property 'Message2'
        }
        /// <summary>
        /// Test the property 'Message3'
        /// </summary>
        [Test]
        public void Message3Test()
        {
            // TODO unit test for the property 'Message3'
        }
        /// <summary>
        /// Test the property 'Message4'
        /// </summary>
        [Test]
        public void Message4Test()
        {
            // TODO unit test for the property 'Message4'
        }
    }
}
